name: FurBe
description: "a dog mood detector app"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.0+2
  path_provider: ^2.1.2
  get_storage: ^2.1.1
  table_calendar: ^3.2.0
  typed_data: ^1.4.0
  url_launcher: ^6.3.2
  duckduckgo_search: ^0.2.0
  http: ^1.5.0
  path: ^1.9.1
  image: ^3.3.0
  image_picker: ^1.2.0
  uuid: ^4.5.1
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  firebase_database: ^12.0.0
  firebase_storage: ^13.0.0
  intl: ^0.20.2
  shared_preferences: ^2.3.2
  fl_chart: ^0.68.0
  get: ^4.6.6
  google_mlkit_image_labeling: ^0.14.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/models/
    - assets/models/dog_mood_classifier.tflite
    - assets/images/logo_bare.png
    - assets/images/logo_main.png
    - assets/images/logo_main_zoomed.png
    - assets/images/paw.png