name: furbe
description: "a dog mood detector app"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  camera: ^0.10.4
  path_provider: ^2.1.2
  path: ^1.9.0
  image: ^3.3.0
  uuid: ^4.5.1
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  firebase_database: ^12.0.0
  intl: ^0.20.2
  shared_preferences: ^2.3.2
  fl_chart: ^0.71.0
  get: ^4.6.6
  tflite_flutter: ^0.9.5
  tflite_flutter_plus: ^0.0.1
  tflite_flutter_helper: ^0.3.0
  tflite_flutter_helper_plus: ^0.0.2
  tflite_v2: ^1.0.0

dependency_overrides:
  camera: ^0.9.4+5
  ffi: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true

